# Generated by Django 6.0 on 2026-02-06 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-publication_year', 'title'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
